server:
  port: 3344

spring:
  application:
    name:  myspringcloud-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/zhai_huabing/microservicecloud-config.git
